CREATE TABLE TestTableS(
Column_A VARCHAR(100),
Column_B INT,
Column_C DATETIME,
COLUMN_D VARCHAR(10)
)

INSERT INTO TestTableS(Column_A, Column_B, Column_C,COLUMN_D)
VALUES('TIME TABLE', 10, '20/4/2020', 'RAYA')

SELECT *
FROM TestTableS